### ISSUE TITLE
Can't resolve 'react-native-web/dist/exports/ActivityIndicator'

### ISSUE THREAD

**Issue by alec6** [creativetimofficial/argon-react-native#17]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [v] I am running the latest version
- [v] I checked the documentation and found no answer
- [v] I checked to make sure that this issue has not already been filed
- [v ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
With expo start and running "Start Android/Emulator" - starts app on emulated device and on web

# Current Behavior
Failed to compile.
/home/alec6/expo/x3log/node_modules/react-native-modal-dropdown/components/ModalDropdown.js
Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator' in '/home/alec6/expo/x3log/node_modules/react-native-modal-dropdown/components'

If i delete ActivityIndicator in ModalDropdown.js, i'll have a new issue 
Failed to compile.
/home/alec6/expo/x3log/components/Tabs.js
Module not found: Can't resolve 'react-native-web/dist/exports/Animated' in '/home/alec6/expo/x3log/components'

# Failure Information (for bugs)

I think it's a bug

## Steps to Reproduce

expo start

## Context

* Device: PC Asus
* Operating System: Ubuntu
* Browser and Version: Firefox

**Comment by palingheorghe** [comment]
Hi @alec6 ! Thank you for your interest in our products! I'm not sure I understand what you're trying to do. Are you trying to run the app on the web? you could try installing `react-native-web` and see what new error pops up. We haven't tested the app on the web yet so we don't recommend using this product for web purposes right now.

Thanks,
Alin

**Comment by alec6** [comment]
This is what i did.
npm install -g expo-cli
mkdir ~/expo
download and extract argon-react-native-master 
cd ~/expo/argon
npm install
expo start

"Failed to compile.
/home/alec6/expo/argon/node_modules/react-navigation-drawer/dist/views/DrawerView.js
Module not found: Can't resolve 'react-native-screens' in '/home/alec6/expo/argon/node_modules/react-navigation-drawer/dist/views'"
![image](https://user-images.githubusercontent.com/17824271/74973330-84fd4200-5423-11ea-8746-57ab27ff03a0.png)

**Comment by palingheorghe** [comment]
This should easily be solved by redownloading the product, deleting all `^` instances from `package.json`and then hitting `npm install` and `expo r -c` which will start the server resetting the cache. 

Thanks,
Alin

**Comment by alec6** [comment]
I'm sorry, nothing's change.
Thanks

This is my package as i understood.
`{
  "name": "argon-react-native",
  "version": "1.3.0",
  "description": "Argon React Native, based on Argon Design System. Coded by Creative Tim",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/argon-react-native.git"
  },
  "dependencies": {
    "expo": "35.0.0",
    "expo-asset": "~7.0.0",
    "expo-font": "~7.0.0",
    "galio-framework": "0.6.3",
    "prop-types": "15.7.2",
    "react": "16.8.3",
    "react-native": "https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz",
    "react-native-gesture-handler": "~1.3.0",
    "react-native-modal-dropdown": "0.6.2",
    "react-navigation": "3.11.0"
  },
  "devDependencies": {
    "babel-preset-expo": "7.0.0"
  },
  "keywords": [
    "argon react native",
    "argon design system",
    "argon app react native",
    "argon iOS",
    "react native iOS",
    "creative tim",
    "argon Android",
    "react native ui kit",
    "react native expo",
    "freebie",
    "react native argon design",
    "react native galio",
    "galio argon free",
    "galio react native free app",
    "argon expo react native",
    "react native ui template"
  ],
  "author": "Creative Tim <hello@creative-tim.com> (https://www.creative-tim.com/)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/creativetimofficial/argon-react-native/issues"
  },
  "homepage": "https://demos.creative-tim.com/argon-react-native"
}`

**Comment by alec6** [comment]
I don't know why, now it works.
I close the issue.

**Comment by pontusvision** [comment]
I'm seeing the same issue on a fresh build.

**Comment by dineshjeph** [comment]
> I'm seeing the same issue on a fresh build.

Yes I am too getting the same issue. any help ?

**Comment by zyxgo** [comment]
same here for fresh build.. open from expo just show timeout..

**Comment by siemiatj** [comment]
Should `react-native-modal-dropdown` install `react-native-web` locally, or should it use one installed by argon ?

**Comment by palingheorghe** [comment]
Hi, 

Thank you for being interested in our products! I'm sorry to hear this is happening to you because `react-native-modal-dropdown`. Because Android opens up the Web simulator as well, this error persists. The easiest way of getting rid of it right now would be to remove the library and reinstall the app. We will come back with a fix as soon as possible.

Thanks,
Alin

**Comment by siemiatj** [comment]
I even tried cerating my own fork of [react-native-modal-dropdown](https://github.com/siemiatj/react-native-modal-dropdown) and merging all the latest PR's, but that didn't change anything.

**Comment by bldlcrz** [comment]
any update on this?

**Comment by palingheorghe** [comment]
Hi guys! A new update has been pushed. The error should be resolved if you still got issues please open a new issue as this one got really cluttered. The original issue is related to cache so by doing the following you should always get rid of any cache issues:
- Delete Expo App from Simulator
- Delete package-lock.json
- Delete .expo
- Delete node_modules
- npm i
- expo r -c (restarts cache and starts a new expo local server)
- everything should work as expected

Thank you for your patience,
Alin

**Comment by stanica** [comment]
Same problem still. Followed the instructions in the docs and the comment above and I'm still getting the ActivityIndicator error

**Comment by integration-consulting** [comment]
The issue still exists in the latest release as of Oct 1st. 
Any workaround?

**Comment by zolter** [comment]
Have this error too

**Comment by vishakhag6** [comment]
Having the same issue... Any solution?
<img width="1333" alt="Screenshot 2020-10-18 at 3 04 04 PM" src="https://user-images.githubusercontent.com/10935770/96363622-2b384d80-1153-11eb-9c42-6f55e0da852a.png">

**Comment by JBotwina** [comment]
Same issue when I try to run the free material kit for react-native in the browser.

**Comment by haveamission** [comment]
Still seeing the problem in React Native Web

**Comment by lkrukosky** [comment]
Just purchased bundle for Argon Pro React Native and same problem.

**Comment by SwapnilAkolkar** [comment]
Same problem even on date 21-dec-2020

**Comment by sidekechs** [comment]
I purchased the pro version and having this issue.  What can be done to fix this?

**Comment by Naphier** [comment]
Same issue on Material Kit 1.7.0. Please fix.

**Comment by mikevb3** [comment]
got the error too, any other issue where it is being tracked?

**Comment by ap1969** [comment]
Same problem in free version. 

Expo v4.0.17 if that helps, trying to run via the web

**Comment by afeezaziz** [comment]
Hi, I am facing the same problem too. Is there a way out of this?

**Comment by MapleHero** [comment]
Same issue from me :| Haven't found a way to fix.
